# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Remon98/kernel_build@main
      with:
          kernel-url: https://github.com/techyminati/android_kernel_realme_mt6833
          kernel-dir: kernel-4.19
          kernel-branch: android-13.0
          config: cyllene_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: false
          android-version: 13
          aosp-clang-version: r433403b
          disable-lto: true
          anykernel3: true
          extra-cmd: LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip LLVM=1 LLVM_IAS=1
